
# 1st group patching and labelling
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumesnapshotclasses-sa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volumesnapshotclasses-cr
  #namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["get","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volumesnapshotclasses-crb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: volumesnapshotclasses-sa
    namespace: openshift-adp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volumesnapshotclasses-cr


# 2nd group object bucket claim creation
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: obcs-cr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: ["objectbucket.io"]
  resources: ["objectbucketclaims"]
  verbs: ["get","list","create","patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: obcs-argocd-rb
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: obcs-cr


# 3rd group oadp backup and restores
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backups-restores-sa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: veleroresources-cr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: ["velero.io"]
  resources: ["*"]
  verbs: ["get","list","create","patch","delete"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]
  verbs: ['*']
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backups-restores-crb
subjects:
  - kind: ServiceAccount
    name: backups-restores-sa
    namespace: openshift-adp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veleroresources-cr  


# 4th group sealed secrets auth (not AWS)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealedsecrets-sa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealedsecrets-cr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get","create","update","patch","delete","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealedsecrets-crb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: sealedsecrets-sa
    namespace: openshift-adp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealedsecrets-cr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealedsecrets-argocd-rb
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealedsecrets-cr
