
# 1 group
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumesnapshotclasses-sa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volumesnapshotclasses-cr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["get","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volumesnapshotclasses-crb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: volumesnapshotclasses-sa
    namespace: openshift-adp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volumesnapshotclasses-cr

# 2 group
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealedsecrets-sa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealedsecrets-cr
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealedsecrets-crb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: sealedsecrets-sa
    namespace: openshift-adp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealedsecrets-cr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-sealedsecrets-rb
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealedsecrets-cr

