apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: oadp-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: openshift-adp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: oadp-config
    repoURL: https://github.com/javierbareapalma/odcn-helm-sealed-secrets-oadp.git
    targetRevision: main
  syncPolicy:
    automated: {}
