apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: oadp-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-adp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - oadp-values.yaml
    path: operatorhub
    repoURL: https://github.com/javierbareapalma/odcn-helm-sealed-secrets-oadp.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
