apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: volsync-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - volsync-values.yaml
    path: operatorhub
    repoURL: https://github.com/javierbareapalma/odcn-helm-sealed-secrets-oadp.git
    targetRevision: rh-jbareapa-oadp-aws
  syncPolicy:
    automated: {}
