{{- if .Values.createNamesapce }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | quote }}
  {{- if hasPrefix "openshift" .Values.namespace }}
  labels:
    openshift.io/cluster-monitoring: "true"
  {{- end }}
{{- end }}
