{{ $namespace := .Values.namespace }}
{{- if .Values.operators }}
{{- range $op := .Values.operators }}
{{- if $op.operatorgroup }}
{{- if $op.operatorgroup.create }}
{{- $og := $op.operatorgroup }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $op.name | quote }} 
  namespace: {{ $namespace | quote }}
spec:
  {{- if $og.namespaceSelector }}
  selector:
    matchLabels:
      {{ $og.namespaceSelector }}
  {{ else if not $og.allNamespaces }}
  targetNamespaces:
  - {{ $namespace }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
