apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: oadp-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-adp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: oadp-operator
    repoURL: https://github.com/marpears/helm-sealed-secrets-oadp.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
