apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: sealed-secrets-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    helm:
      parameters:
      - name: fullnameOverride
        value: sealed-secrets-controller
      - name: containerSecurityContext.enabled
        value: "false"
      - name: podSecurityContext.enabled
        value: "false"
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.9.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
