
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: oadp-obc
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  bucketName: {{ .Values.oadp.bucketname | default "oadp-s3-bucket" }}
  {{ if eq .Values.oadp.scbucket "openshift-storage.noobaa.io" }}
  objectBucketName: {{ .Values.oadp.bucketname | default "oadp-s3-bucket" }}
  storageClassName: {{ .Values.oadp.scbucket | default "openshift-storage.noobaa.io" }}
  #generateBucketName: this is a prefix
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  {{ else if eq .Values.oadp.scbucket "ocs-storagecluster-ceph-rgw" }}
  storageClassName: {{ .Values.oadp.scbucket | default "ocs-storagecluster-ceph-rgw" }}
  {{ end }}
