apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dm-restic-secret
  namespace: openshift-adp
spec:
  encryptedData:
    RESTIC_PASSWORD: {{ .Values.oadp.dmresticsecret | quote }}
  template:
    metadata:
      creationTimestamp: null
      name: dm-restic-secret
      namespace: openshift-adp
    type: Opaque
