apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgBb3i6G75IYmTlBFQtGxaG1635/0eZ58dBun/cttvS89HeeWyasVcaOT34hEaYhJHuSCZVV/5NuWiIXtPZkd1/6AVs/pwJcUgwopHdk9B5zsitGtnQTjemmOGDwin124eqw590HiZiMp/Cu6xYkR+sAiThL3hby922g7+MbfiLaILDBIFiewUPPl7yQ61xLamZVNmLCbgbU+nl9mEF/4OUp6wQUtWtiVYrsMJ7VSH555WXZz5CSoUPsQEdbkLVGideBERGtrEClK5cIMtI5NPitnPSia5YMg95hrMSSDpEULZOHO4rDRrGJJHhMZWddsNotZlajIO6TOY4No6vfmMJQhTkzl8JDda6ii8zjp0iE0EmwGI5eVNAjp4B9CVf0SHRlPWvBDMnr42qGnBsnR9vtgW+24bEOZdUKCxhkVYZDfvhcz8FjhU8gKTnhdwrgI94spvUZ54xI4QBtCIo4S6Va+kkFjCSZ55b3XxEptkhvMYevJKBHfFk9ztyueZ5e2d1tV5pb3w+cPdFr/YDlB/X06oPaSGQqkKOp4O7aKH5jOD0174T0JR3XSm0EjVeI1nczoS56XQwIotCkF4J6cf4pmH0ynbhKUEHOWKAmajUb+YgnAhFKf59nXrKs0vwObapG4tXVhp9mfQYnjQp+ZlUc0imjtOPM1f597lyZmSJKP8Vcss7TYfwHhgwR9CrcwRRgwpVKWekazDdncCEHLAuizEaQ2zSRRMG8//aSuqg4O4eLsHjUzCOAayLDq7qIBjFHrgVNPfD5pEkehIbCm5DVMSUimth6YjgAC4lCA+nDJfO9aHtkesGBNIuX/O3ox55gr5i/nXaGvy4nlX5QKsevVJ1VsQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: openshift-adp
    type: Opaque
