apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgAg1sl1tuJi7gklTNRb05SwzX6dxIfJ5GM08BbFUWp1JnuXS+FtclNV86rXnh0lbsCR+3+DlzSvhPnwJ7CopI2gYqg0cDjrf2ga8Pw1mtb/QTPDvZpid+O0H8eAgj2bkQhEBpN4eOjFKQ/Yrpu/YKObjb8FYtijtN9VsMV9LGHo68F3keaIDcxM9CCkWdpqlnifXCC6YKjhIzJg1fKESj+UMpUeN0zw0+SyJOVz4nThqVpwPNx7bSBAuh/xxzYqFfTE3Bjp7Z4/dAE2ln7W5SNL7Jtdd4WmsfzMfAV4VcYuygrmelrVAutro9zvPmETJ+gn1MMCRrR7GrDIrqbjMPP3l4AY6Tq+JOmf5fIDhtLck656KnaAzVv/6zU+PXNqvG077qePKCk/gz0BkVwz2whHuR00bANj5lMI+fVE8xlKAuvM8j8pcR0L7vLE/UiyE/F7l716CLg7e/DaCKjBBifcTVNGTy+6JJpSyQ0aSuFKHsJleLd90JHVWcEeHGda8dH77Ru8GuIcvYxjmuepjz1YWiU61MAjvqMTbBkbzWN2/2+JqouAqZOATI4VcerNBUvGD8DhwRDalkS6RF0UMVYwJjwA8yKIvXNqP+my9LsBwZI53UvZ2BwzP3/TL8xpnATKR+oW3WvIkrkMceV+t7koobcyglX9E2hkWwEjOaExiAUksIn2XnmnIEp86knQpOeBpcJjrl1YuG3ZgTdbx6TfBIX73TJSDyDmHMKVFhYxQx/M00C/DwZS+Zvae2uUGQZZMaX1vbZIfCQhXGy+t11Rstg5a/PkB4XF3iNkQIt5kU0ZtqskmreXB3bBGSVeEz2Jk+EGwHPjwlf/gcJ0CfsT
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: openshift-adp
    type: Opaque

