apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: {{ .Values.oadp.cloudcreds | quote }}
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: openshift-adp
    type: Opaque
