apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgCPACFEc7UNThU3uh9QTfXnWgePcyNQlNSoCW4tG5EfYuJhCfBzJYTIcHju41BZTh5YU8HF1Sk7GJmtLQaaqc4Jw8P6+T5jqtKik3xiNWRDLGiWjEVbwRP8GAWnKfM9R6XB6KGlVSsu4yLIDT/aUSDEXPAJhUCw3qga9P8z3asSlokfK4jDUfQtn//6VWO+EwskxyknrMIpeGvgR1C7YOr6RMfysiXPeCvdwnp2M2toiLLf3jaPIzOVAW7uAK8YLJvZGC5dYD9wjGnuNq3HooFrxco8ppb9EAyjbOCoFMk+zssP3/ZtGonkI8om4U8F5pp+U2lG4AcPyJaJRaeQx1iRdo3n87EE5ymu3FpfKZgGCXiQWtnbj8cH+I80Q6TqAyiYlKnoUkWBbODO8m5eMJT+gJeS/qXPWHh2W0U3IAiuV3UqKdSnr5cKldDeMgdOKkxWvc2UGd/SUlsuckLO4TwWUVfSOAYrQlVHTKjlUqk4t6SARy+JvhPCxnduL6hNGovo7059X0uuskrFzX9kw4pZdBKVGwk7eAiGy8/m9OGO3Ze3m33VnpZlAUvK+wRaaqeNBKDGOYAOl/YUq63ogw80bavjzZvjnqG/GA6z+FCnM73HjBls/sy5lhX4pli8px1qqbgLuxVMqJKgK/y49GcQa1LTSmaJx5GTo/ixfLQQJwRkWRgTCZDrmaSgsc4jXWb0jgdjjAUjM835M/766MpjgCSiDYdgkWguV0VDz/rB2VZQExh7p9ZFBh8zG1gfOQWo2CBlSOkw3hVgV3HVaCtMRpC5Dhki2pmmGexpRzeGgkXfGI+utM2fWocUZSANWKmwDkyeGkdFT5jXdhogq2G3BFsAzw==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: openshift-adp
    type: Opaque

