apiVersion: batch/v1
kind: Job
metadata:
  name: cloudcreds-stuff
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    compare-options: IgnoreExtraneous
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift4/ose-cli:v4.11
        imagePullPolicy: IfNotPresent
        name: getting-cloudcreds
        command: ["/bin/bash", "-c"] 
        args: 
          - |
            echo "Getting credentials from 'oadp-s3-bucket'";
            oc extract secrets/oadp-s3-bucket -n openshift-adp --to=- > temporalfile;
            jb=1;
            echo "[default]" >> temporalfile2;
            for item in $(cat temporalfile); do
              if [ $jb -eq 1 ]; then echo "aws_access_key_id=$item" >> temporalfile2
              elif [ $jb -eq 2 ]; then echo "aws_secret_key_id=$item" >> temporalfile2
              fi
              ((jb++))
            done;
            oc create secret generic cloud-credentials -n openshift-adp --from-file cloud=temporafile2;

#            ACCESS_KEY="";
#            SECRET_KEY="";
#            while [[ z$ACCESS_KEY == z ]]; do
#               echo "Wait for oadp-s3-bucket to be created, sleep 2 seconds"
#               sleep 2
#            done;
      serviceAccount: cloudcreds-cli-job-sa
      serviceAccountName: cloudcreds-cli-job-sa
      restartPolicy: Never
