apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgCzBHQ8yCIgTfvd5JV9UqyGBld/wXwQZj6CZIIUaeM9sTtz0uOeNW9H72pwwiWN+/0i7NPPE6C/Z1rUuvfS4Dw0Pn+AY35uvlUepp10k/ap5xbh7qenAU12eGQM5tE6mrOl6jT32FDlrMoehHaNkp7NmxTXj3svM1JLI8H/ZdIT6fc71X3f1DNJijVgL7/uv8IAEoNJhL01/qtY7fRUxmV6xO3aa9Eqgvy8jw6ZHK0zWMcV43wIQ/GQTQqcWm4i4JlrKpwdrj/ncY6kboxHUAoAN+NajvdUBcwpe+qKeeiMo8Pm+7m9O2ekB1lCYMDewtmby5va1t/xqaJTet7KsESB9aZ1QXzJDR9/ckyH2LOzmJvlYKq/x1nf7A3vPdBNdY5N66HRC9gjuG4u9SkJ8AiB5EcX89vyifuzIAbGyP5zbgVtjFKjFIE0M9irL4zTSzrH1YTKry7q1ligPPOfiCk1FdeytZ9sr6A4n3jfyBMWVHUFYkt5r0HeRXpQTBFyDUTARQV1Fl7p4z+c92WVG7O8qcUWm7g5+GZefJbBpoy2+/UXfX7kHahtX5gmab7+v98hp3xeM0AItCJrbt6BL+EeA7FQ8no+HpT0bURUXeQsAXdQ9h75URj+N3Tw1qpWj+LrBuwH3qEKT9LkDUl1VJk2Fs4AlCbNbaXP+qLqQkUg6Er2q4Lnj3zLuY6lRQ6AiLLY7qj1j76DFSbat0ZU0zmNr1XBBYJdVNAc2O0kTW7fgWAwzch6PeuxJCB4WVX05p55S77m7UMrWH09FnTccCjgJ7vksBSsB1ONBmZpjnDXWFgGx3ZRY3ETS8AEMNKCgdxqXyKkZeNLfLPFdW4dnAYC
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: openshift-adp
    type: Opaque

