apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgAdjnkLWrkNwowuTAIxmgIXyOd2ryrEDBauYpv3E/hFtjeZITB1/LcFBpo8hJfmbtA1F9mI/g+loI8aMnVaC2ou9CPFAKT4i0FpK873SJhquu+SZeYtRi6mIfF/22p6YC0jXFr59uvorwf5nK7Z0BuaqjeFlSGQglBWHO79Ow2r/u0Wx1acKXG8b6ScqmXI++Sq9QhEUHQMamYkLMSoIXsucDCPtCgisfBiImPQMXFzEsOk3Ujf2rPvWETF8s2DuEebmATUteEr7/DgP5yNKZwbKkuEClJwJrTnwYiK6+cd/QG24Y/AThsn9skV6zdhlNzKxwRarwewiOMuPOegKLdEDwrpKjs6mYfe5vWS7YIVshp3mkTrLZh7cvx2+nVlp6Q2f5bKte4MKhARlOQQJvd4ohMLCFPTYBYcUIvaDs5iKMdT1OlTQybZe+5WRR+58NCmHQzkXnD8zYz3lRDfZNipmPLjDrnb9NY7k2IXAQVBxo3vWFOhUIwagt0QGuDxDJduUQBCOAkRl3tLMp/U7RqWyqnbpm4u4+7WmcKasUrCgul5Mzy2d3hyiH85N8rhFAh7XwpxVrK5HeP6VdvPnossNsmnBT+ZcFjVvngcGY9FXdjKV1QTDLI42RUSdOaSc+f6tzIiZlWA0Bbi2ZEjn00m4PU6pj3KZ/PRE+jukqUCIGyL1uyT09akK2lXCTP/UGnHZcJ2MwS0nl4gSbHgZB/qBy5pMf/nAAfwq+0dSYCD6rxa63sx1Cf50RJYgSPqsgJ01tqxJ5MKYwopfIGV2gyFNv2BqoLxN1bme17in41yUH0bTK5QpdD9rmeBFLIMHtxIHS+PHXLe6RNQpE9w4YIu
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: openshift-adp
    type: Opaque
