
apiVersion: batch/v1
kind: Job
metadata:
  name: cloudcreds-stuff
  namespace: openshift-adp
  argocd.argoproj.io/sync-wave: "4"
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift4/ose-cli:latest
        name: getting-cloudcreds
        command:
            - /bin/bash
            - -c
            - sleep 3
      serviceAccount: cloudcreds-cli-job-sa
      serviceAccountName: cloudcreds-cli-job-sa
      restartPolicy: Never
