apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dm-restic-secret
  namespace: openshift-adp
spec:
  encryptedData:
    RESTIC_PASSWORD: AgArwf86+jEcxbIHxjkL9W3++hfNPhSsgKpP5CWHBuUnYAsPxNvi0uPZF0XOBP1vWZbMfHbNp1Tj/AR+b4YZ6jayIvZjij3W6mPj3DTWrgBEKYNbiHzQc8R70GNrhG8mZ/Qm59fAz8v4w/cYeWPzP8p90kRzomOzxUrq4ErKuovUS5/W0t86D4ORobI61bHWokYWX6pduj1vUTJQuorS1EPE65FZ1Y9kinFS9OH6ocDX0t8bF8U1nPud2OD2Wfte7weTd658haA4mnrrHpKaU112zczl/kBAZwVBvcjJG4a1sN7X70Dg+AZFTdzpfB7upZf0kaux2Hz3WP2bcVlmPRNwFm+jerRfdtNsxQW4/qcnlzdEdqDD+nF7RQC88rlrTWa+2iYIOWqhLvXWqPcqYAbWBYNmOGxf61JK3/kX37XnPzpzD24KQhUgQoEtAe+prnuKSm8YGn6/tp3Tnztac5Pf+RoqKOEBRpy7pI+hp60s4RwfeFLwDH4sFjUncmm9ma1kd+US+iw63tuy1wMxSUdqrpkN9Aq1s6O1pOsYgLOI7H6fTeDVOBtSXHQkuQxwaX0dsl9dGdQCN3eAsoGR64R4bxvPAYJyo7ZnG1fcKr1j83lRz4WV8dAUa0HVaZIztyF6rHTtJbi69hqjnLrMDyAN9q4iQLTlUGxet2DmAgjuu5+XJcgigcOPS2LzF/uuQUah7qekuXf95Tz/5mBLSg==
  template:
    metadata:
      creationTimestamp: null
      name: dm-restic-secret
      namespace: openshift-adp
    type: Opaque

