apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dm-restic-secret
  namespace: openshift-adp
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCpM/yMZoklPjjS1f4BaddAunECqwqgfwHblMBkMnlv8+hdXtwGTBtlaKeHJzKNLlxN6hVfYlw+wZCclnd/ieylyApoR7Njdv0OEo37JSCIX4IdxPxPCJnL4sLntzCY+kBBUBCetcrvGNfeGRvqM2OG6HG+UCVLFGcenwJan6g+NbPPKZfKmgUn49jMsilOxoZiIINAot26wNggDVeaptaJknK+/nUxnmaYt6jpL/HMWmqILYy0YXNLIGFnfauCLNOPTLKf0jV4dOWw2ZaHQ63vVUFvq4trR/tKLNjeXWezFPL5z25Oqlztqo2ggsenYvfjQgYet2DKfcndJmkwFAIOUH6eo3aMHNtVnSbtlEknaQUstVFVq+Yv0bEuhbuRYQ2hg3/OynL8tZbQQINqzamllgkpJ6ugPu0xJaCRqe4MMuby88Bk2EDSZmjCnh8p+IFVY34DaFVbmiM6nW6BthHt/C8PFL16LCdN4iw9WjJ1SmwMdCxkXnmyjwtm3sX3Y3S3aasT+u+3MMt3qQ+jgtUkYN44zhdVaAxml2fC3I1WqmI6UuQqBhSyZjFwJwaviP63G/FYsiT5ehoCJ0Px+NLsuEoXRKngisZ8Me+x69+RIUQFeEYCXCmb124vpmICrPPqRCnQ4/OG+QXU3HsDYrIaLHBorPpRJbRLOnJ63wZlRDI69owzwMjvEMxQAd7Aq32z7UDwAkUQVLNl52x3xKw=
  template:
    metadata:
      creationTimestamp: null
      name: dm-restic-secret
      namespace: openshift-adp
    type: Opaque
