apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dm-restic-secret
  namespace: openshift-adp
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAX0RYJTUntIiv2OkRJsHZg903xI0p/vtngKI6nCvOWYXX7sXCKGu6BWYRpxiAkssRLUShmoSkwqthkZhmCrgHxK8JZ936pl30B7abdoW2wDlAlxB8EhyWW9JFCWGXTyPDz+vNL4esX5+h3igZsw7CROg0vDcLNNAMYaxo/nXdO82Jp3CWEXvOOoByQuNl+XZ8zvLNdO81JUasEprhiZDAjV9j9INKorY65gAcHedeHU3o7w3EA4hVZLcYgpP+SYtZ3WSzauEuAPUZFp/w0ZUNLD5+doozJxprOPD19fNPaoXn9XP4XV/xlWXk3L8zJVa9ktMuAYSXHnqC5ldtYiE2Foaw8RtKY62PG8rENJJNB1Ng5OE5ArRn0Sw2Ubas3lhNfCrEzpfFUH3yIXNjsaPMbjdeiOjj2u5n77nXjzOZw5xrekVVQIUdmVzPrmFT8Htmqgo1JnuoRfk175/EOoytFUaIvV+2AORw6ScPsrvt68ymhlxGNAbhPVg/cKTWVJPi1PTt+YJBbP2nc/kl1/o1LDZoMTrzIJ316OtyykAWwGJvl8NMWDXtA4dFqP8YjAl47+8EbUAoteuXCBelV+T75AMHIbP6wOnEuZa+vijIHFlyWKuFlZf/6dxn7apRXX/HQhSq04G2h/0CX1kNUdyO2TdPmRRAslE7K8B0oXfmcSGqMBf7xysgS81UbUeOhdyCLkvxqHXEvP/MEnZowdPs=
  template:
    metadata:
      creationTimestamp: null
      name: dm-restic-secret
      namespace: openshift-adp
    type: Opaque
