apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: {{ .Values.clusterName }}-dpa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  features:
    dataMover:
      credentialName: dm-restic-secret
      enable: true
  backupLocations:
    - velero:
        config:
          profile: "default"
          region: {{ .Values.dpa.region | default "rgw" }}
          s3ForcePathStyle: "true"
          s3Url: "https://s3-openshift-storage.apps.jbocp.sandbox305.opentlc.com"
          insecureSkipTLSVerify: "true"
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: {{ .Values.oadp.bucketname }}
          prefix: velero
        provider: aws
  configuration:
    restic:
      enable: false
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
        - vsm

