apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: {{ .Values.clusterName }}-dpa
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  features:
    dataMover:
      credentialName: dm-restic-secret
      enable: true
  backupLocations:
    - velero:
        config:
          profile: default
          region: {{ .Values.dpa.region | default "rgw" }}
          s3ForcePathStyle: "true"
          s3Url: "http://s3.openshift-storage.svc/"
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: {{ .Values.oadp.bucketname | default "oadp-s3-bucket" }}
          prefix: velero
        provider: aws
  configuration:
    restic:
      enable: false
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
      featureFlags:
        - EnableCSI
