{{- if .Values.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | quote }}
  {{- if hasPrefix "openshift" .Values.namespace }}
  labels:
    #argocd.argoproj.io/managed-by: openshift-gitops
    openshift.io/cluster-monitoring: "true"
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
{{- end }}
