{{ $namespace := .Values.namespace }}
{{- if .Values.operators }}
{{- range $op := .Values.operators }}
{{- $sub := $op.subscription }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $op.name | quote }}
  namespace: {{ $namespace | quote }}
#  annotations:
#    argocd.argoproj.io/sync-wave: "-3"
spec:
  channel: {{ $sub.channel | quote }} 
  installPlanApproval: {{ $sub.approval | default "Automatic" | quote }}
  name: {{ $sub.operatorName | quote }}
  source: {{ $sub.sourceName | default "redhat-operators" | quote }}
  sourceNamespace: {{ $sub.sourceNamespace | default "openshift-marketplace" | quote }}
{{- if $sub.csv }}
  startingCSV: {{ $sub.csv | quote }}
{{- end }}
{{- if $sub.config }}
  config:
{{- if $sub.config.nodeSelector }}
    nodeSelector:
      {{ $sub.config.nodeSelector }}
{{- end }}
{{- if $sub.config.toleration }}
    tolerations:
    - key: {{ $sub.config.toleration }}
      effect: NoSchedule
      operator: Exists
{{- end }}
{{- end }}
{{- end }}
{{- end }}
