clusterName: odcnoord-ocp
 
###
# OADP Chart Values File. BEGIN
###
#
oadp:
# dm-restic-secret
  dmresticsecret: AgAGg2nNVZFqP0kd7N7FjmRGuHppVGZvO2WVsCGHAjVHBYz94TLbvHk3btzqsbmW4jWgz5J4BpFm7RYkVCuTrZSiHCGl0yR9NfyDfC0BkDqrAI2wS9Fu6Tfskb1hfV5pK5CmhvaP6k5Eg7keA39RcwN7DySTRonNqfQI+rzYS8/FR+Cd7br3q/B2sYKP+6uYika3Gp1eStNjw34rEWiffSfCavQvzpNsxQJlbco/YmJY8rYR1449FlLMdvcbqtqlKuN+xToQEjTQdGwquuaDA23tqaLN4hkgp58Cd1Pf1i3jlRjuvOz6JTHCobAhRnDFiExheYcu8mvNOd5CgjhxvbBAa+3MJREeMRgxaUPB1r2nSveShuDiIMikWzx+EvuYCp0y+bbShl7gSKR76vGhiDxLRkFcTG4ZfqV0JGh8eE57mSn8eVCql2jAeSgQZqP8MoFI/6qFgvveWxJ8A9TKypLM6ecHp2pzNO6RhB+S/sjqivG/GfzjwfMWGAoX16tNqeOkQSOuvPloOqzC2u1pc6PrxJ6c7bkjAayTUDZEmcoGotciydJYglKMFlo0wpYOZcx6eNrNkucBQioFTUKRs4d4qk4W7CZmj0CP6gTElz1LawepaeEsKH1ZQERw2fcEk7N2IDPkE6WQ2J0OmxivSaliovOfXKXzezd57hFh6CBVGFZ0x03CaTxuComIGxRD/ov7jXvRX0ffr/mnYT4ARjY=
# bucket name
  bucketname: oadp-s3-bucket-69
# StorageClass of bucket
  scbucket: s3aws-standard  
#
  cloudcreds-awsaccesskey: whatever1
  cloudcreds-awssecretkey: whatever2
  cloudcreds: AgA0o8ZtwHYksmXBw8q6Zdz/g5b+8ZK3diZwOno1v1tUzSZXkNyRWB0GK8dvPuzURNhxngaohxA8NfCpmozryh9fubl6Bd0dxW/m7v5Hv+gRq+bdTTRsLeGXvmBQo5Qouxi2e7itkUDdL4uSaB+CbgrePVJC87EnD9t000S0LpJKDKcOH4QfobrEWspXV1s+Kr/M3KNk9QOqGOBupTY/WRJJ81ZOVtGXxtlcICyQ2I5G6SmRsDNEprn3xbx6JM2uwfQmvybwfx+8tZa0XHvsgoBEYeE7u9UMFM5bJKiulh5Q5w1cSd4jxtBwelE0fm9v7KWqNXXCzlzz0pL32S+6ZCyJzAsYUaGcVKtzHr4aCOvo/3Uku0cnp8Ke3SOVUo1X6cBoc7a/OQVglCilWLUizG/YsDy+rnn2ksz7d/7GKcCO5FVIuaFOryEPe7p66kKJk3M+YGBUXAmXo8vMMYModwYWM7RRRtgVPFMxtnjid3duEbzPGjGqen1cPXYvI25yXUvCMl02r0kG/YKP23mEHP1vblm9E+HRpNOSgYqYK8BIjq/2MD2p32buIGteU0valwQXCkO7hrutwRaFdj/v3JcyNk9oEKbRUm3pRuRFeh6WUxg6d/Q3HHCbklJjkqkE+gu489dGkblJMoYAinRHrxIk5sNoZBq1LeL38nH5XwRSB0kAedZus8qWnAb7J1DyiKTVZPPSlLs4AR2I+toxxswBEsQ8uQEoTInFK1P2//DBF59b4/Jx1B8ZyC41vJr+GADdJ1xODBAtsVT6pkLm3QYfnDxn67OEHfUpiAeKVQhq0K9N9r/EACsEjeM98uY5LfHUY+h74k6kKVtn1pyNcvcA7CkNFA==
#

dpa:
  region: eu-central-1
  s3Url: ""
  s3ForcePathStyle: "true"
  insecureSkipTLSVerify: "true"
  nsprojecttobackup: mysql-persistent
###
# OADP Chart Values File. END
###

