clusterName: odcnoord-ocp
 
###
# OADP Chart Values File. BEGIN
###
#
oadp:
# dm-restic-secret
  dmresticsecret: AgAGGMEzoaU/huOEeJlVqrJMOCgKfOi/hO3KGk5OkpRCq8zqS8UMiNBpcsycmDZO9kfyeQmnXBQS9nLdt6d5ly2iC+B+nNXgmrj1tz7ftakhSEZB/zEoPotUwYE+a4DRr6vLUTaXYhTY7kK5ee2R404N7XzUkRATpukBMDgrux4qHRMdJZTwciSmWFrwl4ovWPbYDqWjkt+to76aC3aDtO9NFOjo4JQcpi53qBkg+bsW0nQvamFJ+cJOXYj2hJ6Fe1tjHQGiaZ3wCNqj6iYnYuDWRyLsFLXqGOXKmCdloUbFXXTfbCi+PLKm2CDr2niagqKYqRVd38gkA2ARj0qZk+hBcZdkdoRRQR8c0HTweJNttWGnmUQpDyQU/TbThpKoYV0FbfT0bRYVXH4+xOkkYyucfmuasmgEjvUHNXID8JqkdsiQ3upRDmnRqkhQXuZoHhvwPdqG5RalHdElJ+PWGdQvLSGsg9RrFDF5SkoYFfh2qtBZGHnxZwDVNUQTTsa2RryWRoGLx41wMTr7eny9Ta/6C/mmnOtWAUn8WEsLTKs34rW0tTGL8THUn9jZunquNmkq4+sESSOhTMrits8UUzxFyPdgCA7ZvesHSWezOBKQ5WThsuZMS9pBu/6KpgBSKgG2SWSd3Kd0DX31Vf0Otj6VML3c1jIzcWvu22O6hnzMl6q0lSjyPRvSsp6rrniNugwxr4zHJi7/IZu4LHeF900=
# bucket name
  bucketname: oadp-s3-bucket-69
# StorageClass of bucket
  scbucket: s3aws-standard  
#
  cloudcreds-awsaccesskey: whatever1
  cloudcreds-awssecretkey: whatever2
  cloudcreds: AgA0o8ZtwHYksmXBw8q6Zdz/g5b+8ZK3diZwOno1v1tUzSZXkNyRWB0GK8dvPuzURNhxngaohxA8NfCpmozryh9fubl6Bd0dxW/m7v5Hv+gRq+bdTTRsLeGXvmBQo5Qouxi2e7itkUDdL4uSaB+CbgrePVJC87EnD9t000S0LpJKDKcOH4QfobrEWspXV1s+Kr/M3KNk9QOqGOBupTY/WRJJ81ZOVtGXxtlcICyQ2I5G6SmRsDNEprn3xbx6JM2uwfQmvybwfx+8tZa0XHvsgoBEYeE7u9UMFM5bJKiulh5Q5w1cSd4jxtBwelE0fm9v7KWqNXXCzlzz0pL32S+6ZCyJzAsYUaGcVKtzHr4aCOvo/3Uku0cnp8Ke3SOVUo1X6cBoc7a/OQVglCilWLUizG/YsDy+rnn2ksz7d/7GKcCO5FVIuaFOryEPe7p66kKJk3M+YGBUXAmXo8vMMYModwYWM7RRRtgVPFMxtnjid3duEbzPGjGqen1cPXYvI25yXUvCMl02r0kG/YKP23mEHP1vblm9E+HRpNOSgYqYK8BIjq/2MD2p32buIGteU0valwQXCkO7hrutwRaFdj/v3JcyNk9oEKbRUm3pRuRFeh6WUxg6d/Q3HHCbklJjkqkE+gu489dGkblJMoYAinRHrxIk5sNoZBq1LeL38nH5XwRSB0kAedZus8qWnAb7J1DyiKTVZPPSlLs4AR2I+toxxswBEsQ8uQEoTInFK1P2//DBF59b4/Jx1B8ZyC41vJr+GADdJ1xODBAtsVT6pkLm3QYfnDxn67OEHfUpiAeKVQhq0K9N9r/EACsEjeM98uY5LfHUY+h74k6kKVtn1pyNcvcA7CkNFA==
#

dpa:
  region: eu-central-1
  s3Url: ""
  s3ForcePathStyle: "true"
  insecureSkipTLSVerify: "true"
  nsprojecttobackup: mysql-persistent
###
# OADP Chart Values File. END
###
